apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: saltmaster
spec:
  provider: vault
  secretObjects:
  - secretName: saltmaster
    type: Opaque
    data: 
    - objectName: SALT_SHARED_SECRET
      key: SALT_SHARED_SECRET
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: saltmaster
    objects: |
      - objectName: "SALT_SHARED_SECRET"
        secretPath: "apps-kv/data/saltmaster/sharedsecret"
        secretKey: "SALT_SHARED_SECRET"
