---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: saltmaster-keys
  annotations:
    nfs.io/storage-path: "data01/saltmaster/keys"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
