apiVersion: v1
kind: Service
metadata:
  name: saltmaster
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.62
  selector:
    app: saltmaster
    part-of: saltmaster
  ports:
    - name: saltmaster
      port: 8000
      targetPort: saltmaster
      protocol: TCP
    - name: salt
      port: 4505
      targetPort: salt
      protocol: TCP
    - name: salt-bis
      port: 4506
      targetPort: salt-bis
      protocol: TCP
  allocateLoadBalancerNodePorts: false
